project:
  type: website
  output-dir: "../docs"

website:
  title: "OpticalBlochEquations.jl"
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Examples"
        contents:
          - text: "Blue-detuned MOT for CaOH"
            file: "ipynb_sources/Blue-detuned MOT (CaOH).ipynb"
          - text: "$F_1 \rightarrow F_1$ cooling"
            file: "ipynb_sources/F1_to_F1_cooling.ipynb"

format:
  html:
    page-layout: article
    theme: cosmo
    css: styles.css
    toc: true
    code-line-numbers: true

freeze: auto